name: staff_attendance
description: MVP for attendance with GPS + admin settings
publish_to: "none"
environment:
  sdk: ">=3.4.0 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.3.0
  firebase_auth: ^5.1.2
  cloud_firestore: ^5.4.4
  firebase_storage: ^12.1.2
  cloud_functions: ^5.2.0
  firebase_messaging: ^15.0.3
  geolocator: ^11.1.0
  connectivity_plus: ^6.0.5
  device_info_plus: ^10.1.0
  path_provider: ^2.1.4
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  intl: ^0.19.0
dev_dependencies:
  flutter_lints: ^4.0.0
flutter:
  uses-material-design: true
