name: locarb_attendance_web
description: LoCarb Attendance Web MVP (username/password + admin approvals)
publish_to: "none"
version: 0.0.1
environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.3.0
  firebase_auth: ^5.1.2
  cloud_firestore: ^5.4.4
  firebase_storage: ^12.1.2
  file_picker: ^6.1.1

dev_dependencies:
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
